# Generated by Django 5.2.1 on 2025-06-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_visita_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descuento',
            field=models.BooleanField(default=False),
        ),
    ]
