# Generated by Django 5.2.1 on 2025-06-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descuento',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
