# Generated by Django 5.2.1 on 2025-06-14 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_descuento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/', verbose_name='Imagen adicional')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='app.product')),
            ],
        ),
    ]
