# Generated by Django 5.2.1 on 2025-06-14 14:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_imagenextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenextra',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagen adicional'),
        ),
    ]
