# Generated by Django 5.2.1 on 2025-06-15 03:38

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_imagenextra_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagen principal'),
        ),
        migrations.CreateModel(
            name='ImagenTrabajoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagen adicional')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='app.trabajo')),
            ],
        ),
    ]
