# Generated by Django 5.2.1 on 2025-06-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_trabajo_imagen_imagentrabajoextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
